### ISSUE TITLE
model

### ISSUE THREAD

**Issue by 2151330** [jphdotam/DFDC#1]
![image](https://user-images.githubusercontent.com/41284417/98801704-2793a000-244d-11eb-8d31-4bcddcbb4b8c.png)

Thank you for your work, I want to know  where to  find  the model in the code

**Comment by jphdotam** [comment]
Hi, it's listed in the source file towards the top:

> 1) A slightly modified version of the InceptionI3d model from https://github.com/piergiaj/pytorch-i3d
>     - The name J3D reflects models where I've made these small changes (sometimes I call it J3D or I3D confusingly).
>     - The modifications allow us to feed in videos of various length by ensuring the outputs are either interpolated
>       to be 64 frames in length, regardless, or pooled down to a single prediction with 1D globalavgpooling
> 2) **Pretrained weights from the same repository (Apache license) - as ../../external_models/i3d_rgb_charades.pt**

Specifically, the model file is here: https://github.com/piergiaj/pytorch-i3d/blob/master/models/rgb_charades.pt
